/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Article = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const Cuisine = IDL.Record({
  'region' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'featuredDishes' : IDL.Vec(IDL.Text),
});
export const Recipe = IDL.Record({
  'title' : IDL.Text,
  'instructions' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'cuisine' : IDL.Text,
  'prepTime' : IDL.Text,
  'servings' : IDL.Nat,
  'ingredients' : IDL.Vec(IDL.Text),
});
export const SubmissionType = IDL.Variant({
  'story' : IDL.Null,
  'recipe' : IDL.Null,
});
export const Submission = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'submissionType' : SubmissionType,
});

export const idlService = IDL.Service({
  'addArticle' : IDL.Func([Article], [], []),
  'addCuisine' : IDL.Func([Cuisine], [], []),
  'addRecipe' : IDL.Func([Recipe], [], []),
  'filterRecipesByCuisine' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllCuisines' : IDL.Func([], [IDL.Vec(Cuisine)], ['query']),
  'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
  'getArticle' : IDL.Func([IDL.Text], [Article], ['query']),
  'getCuisine' : IDL.Func([IDL.Text], [Cuisine], ['query']),
  'getRecipe' : IDL.Func([IDL.Text], [Recipe], ['query']),
  'getUserSubmissions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'searchRecipes' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
  'submitContent' : IDL.Func([Submission], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Article = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Cuisine = IDL.Record({
    'region' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'featuredDishes' : IDL.Vec(IDL.Text),
  });
  const Recipe = IDL.Record({
    'title' : IDL.Text,
    'instructions' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'cuisine' : IDL.Text,
    'prepTime' : IDL.Text,
    'servings' : IDL.Nat,
    'ingredients' : IDL.Vec(IDL.Text),
  });
  const SubmissionType = IDL.Variant({
    'story' : IDL.Null,
    'recipe' : IDL.Null,
  });
  const Submission = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'submissionType' : SubmissionType,
  });
  
  return IDL.Service({
    'addArticle' : IDL.Func([Article], [], []),
    'addCuisine' : IDL.Func([Cuisine], [], []),
    'addRecipe' : IDL.Func([Recipe], [], []),
    'filterRecipesByCuisine' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Recipe)],
        ['query'],
      ),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllCuisines' : IDL.Func([], [IDL.Vec(Cuisine)], ['query']),
    'getAllRecipes' : IDL.Func([], [IDL.Vec(Recipe)], ['query']),
    'getArticle' : IDL.Func([IDL.Text], [Article], ['query']),
    'getCuisine' : IDL.Func([IDL.Text], [Cuisine], ['query']),
    'getRecipe' : IDL.Func([IDL.Text], [Recipe], ['query']),
    'getUserSubmissions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'searchRecipes' : IDL.Func([IDL.Text], [IDL.Vec(Recipe)], ['query']),
    'submitContent' : IDL.Func([Submission], [], []),
  });
};

export const init = ({ IDL }) => { return []; };